server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tdp_school
    username: postgres
    password:
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
